### ISSUE TITLE
need watchalive script-tag

### ISSUE THREAD

**Issue by pYr0x** [whitecolor/steal-hmr#3]
to get steal-hmr working i need to add 

```
<script src="/watchalive.js"></script>
```

to my header.. why is this needed, and why is it not needed in the sample app?

**Comment by wclr** [comment]
It is automatically injected in requested *.html

**Comment by pYr0x** [comment]
but not by me.. 
i using this proxying stuff

```
 "watchalive": {
    "debug": true,
    "data": true,
    "proxy": {
      "regexp": "^((?!node_modules|css|js).)*$",
      "target": "http://localhost/steal-yii/web"
    },
    "skip": [
      "node_modules/**",
      "**/package.json"
    ],
    "plugin": [
      "less"
    ]
  }
```

can that be the "problem"

**Comment by wclr** [comment]
it injects only in *.html files, I belive you serve generated HTML by PHP, it will not inject it there

**Comment by pYr0x** [comment]
ok.. thanks... i will notice that, so that i never ask silly questions again ;)

**Comment by wclr** [comment]
thats ok) btw I opened is gitter chat for watchalive you can ask there
